import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/Components/Admin/AuthProvider";
import NavbarClient from "@/Components/User/NavbarClient";
import React from "react";
import "./globals.css";
import Footer from "@/Components/User/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarClient />
        <AuthProvider>{children}</AuthProvider>
        <Footer/>
      </body>
    </html>
  );
}
