repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   id: no-comments
        name: No Comment Code
        entry: bash -c '! grep -qE "^\s*(#|//)" "$@" || (echo "Comments detected!" && exit 1)'
        language: system
        files: .*\.(py|js|jsx|ts)$
        pass_filenames: true
